#!/usr/bin/env bash

set -e
export TARGET_ARCH=x86_64-unknown-none
export zOS_SRC_ROOT=$PWD
export zOS_VERSION="0.0.1"

APPS=("base/loader" \
	"sys/zxt/drivers/hello")


# Creates a memstick image
memstick() {
	zos_xfs_parttype=ab37caea-8669-47e9-9373-425e6de819e3
	rm -Rf /tmp/zOS_build
	mkdir -p /tmp/zOS_build/rootfs /tmp/zOS_build/efi_sys RELEASE

	# Create the disk image
	dd if=/dev/zero of=/tmp/zOS_build/memstick.img bs=512 count=3072000

	# Partition the disk image. The following is literally mimicking the keystrokes needed to partition the disk using fdisk
	fdisk /tmp/zOS_build/memstick.img << EOF
g
n
1
2048
+512M
t
1
n
2


t
2
$zos_xfs_parttype
w
EOF


	########################################################################
	## Split it into two images so we can work with the partitions easily ##
	########################################################################
	dd if=/tmp/zOS_build/memstick.img of=/tmp/zOS_build/efi_sys.img bs=512 skip=2048 count=1048576
	dd if=/tmp/zOS_build/memstick.img of=/tmp/zOS_build/rootfs.img bs=512 skip=1050624 count=2021343

	################
	## Copy files ##
	################
	echo "Copying files..."
	build_install /tmp/zOS_build/rootfs

	# We format the partition and copy files onto it in the same go
	mkfs.ext2 -d /tmp/zOS_build/rootfs /tmp/zOS_build/rootfs.img


	########################
	## Install bootloader ##
	########################
	echo "Installing bootloader..."


	# Next we format the EFI system partition as FAT32 and copy over the UEFI version of 'loader'
	mkdosfs -F 32 /tmp/zOS_build/efi_sys.img
	mmd -i /tmp/zOS_build/efi_sys.img ::/EFI
	mmd -i /tmp/zOS_build/efi_sys.img ::/EFI/BOOT
	mcopy -i /tmp/zOS_build/efi_sys.img base/loader/target/x86_64-unknown-uefi/debug/loader.efi ::/EFI/BOOT/BOOTX64.EFI



	################################################
	## Combine the images back into one, clean up ##
	################################################
	dd if=/tmp/zOS_build/efi_sys.img of=/tmp/zOS_build/memstick.img bs=512 seek=2048 count=1048576 conv=notrunc
	dd if=/tmp/zOS_build/rootfs.img of=/tmp/zOS_build/memstick.img bs=512 seek=1050624 count=2021343 conv=notrunc
	mv /tmp/zOS_build/memstick.img RELEASE/zOS-RELEASE-"$zOS_VERSION"-LIVE-MEMSTICK.img
	rm -Rf /tmp/zOS_build
}

build() {
	for app in "${APPS[@]}"; do
		sh $app/pkgbuild.sh build
	done
}

build_install() {
	for app in "${APPS[@]}"; do
		sh $app/pkgbuild.sh build_install $1
	done
}

clean() {
	for app in "${APPS[@]}"; do
		sh $app/pkgbuild.sh clean
	done
}

release() {
	memstick
}

usage() {
	echo "USAGE: ./build [clean|release]"
	exit 1
}


if [ $# -eq 0 ]; then
	build

elif [ $# -eq 1 ]; then
	if [ "$1" = "install" ]; then
		build_install

	elif [ "$1" = "clean" ]; then
		clean

	elif [ "$1" = "release" ]; then
		release
	else
		echo "ERR: Invalid option: $1"
		usage
	fi
else
	usage
fi
